----
deployment:
  tasks:
    - export DEPLOYPATH=/home/dmt7q0qy3ief/public_html/
    - /bin/cp -r /home/dmt7q0qy3ief/repositories/main_website/* $DEPLOYPATH
    # - export DEPLOYPATH=/home/dmt7q0qy3ief/public_html/
    # - /bin/cp -a * $DEPLOYPATH
    # - /bin/cp -r /home/dmt7q0qy3ief/public_html/* $DEPLOYPATH