<!DOCTYPE html>
<html>
<head>
<?php include "includes/header.php"; ?>
<style>
.promo
{
	
	color: black !important;
    font-size: 14px !important;
    font-weight: 700;
    text-align: center;	
}


</style>
</head>

<body class="hidden-bar-wrapper">

<div class="page-wrapper">
 	
    <!-- Preloader -->
    <div class="preloader"></div>
 	
 	<!-- Main Header-->
    <?php include "includes/menu.php"; ?>
    <!--End Main Header -->
	
	<!--Page Title-->
    <section class="page-title" style="background-image:url(images/background/about.jpg);">
    	<div class="auto-container">
        	<div class="row clearfix">
            	<!--Title -->
            	<div class="title-column col-lg-6 col-md-12 col-sm-12">
                	<h1>Privacy Policy</h1>
                </div>
                <!--Bread Crumb -->
                
            </div>
        </div>
    </section>
    <!--End Page Title-->
	
	<!-- Welcome Section -->
	<section class="welcome-section">
		<div class="auto-container">
			<div class="row clearfix">
				
				<!-- Content Column -->
				<div class="content-column col-lg-12 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<p class="ptext">Please read these terms and conditions carefully before using this Website.</p>
						
						
						<div class="">
							<p class="ptext">This document is an electronic record in terms of applicable Information Technology laws and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology laws. This electronic record has been generated by a computer system and does not require any physical or digital signatures for authentication.</p>
						</div>
						
						
						
					
					
					<p class="ptext">Privacy Policy of the country makes an essential part of the Terms and Conditions, incorporated herein. If you have not yet reviewed the Indian Plumbing Skills Council Privacy Policy, then please do so prior to approving these Terms and Conditions.</p>
					
					
					<p class="ptext">Your privacy is important to us. We do not sell or forward or rent your personal information what you share with Indian Plumbing Skills Council, to any third party for any purposes whatsoever. This Portal does not automatically save any specific personal information from you, (like name, phone number or e-mail address), that permits us to identify you individually.</p>
					
					<p class="ptext">If Plumbacharya Portal requests you to provide your personal information, you will be informed for the particular purposes for which the information is gathered and satisfactory security measures will be undertaken to safeguard your personal information.</p>
					
					<p class="ptext">Any information provided to this Portal will be protected from loss, misuse, unauthorized access or disclosure, alteration, or destruction.</p>

<p class="ptext">Your use of Plumbacharya Application signifies your acceptance of the Indian Plumbing Skills Council Privacy Policy.</p>
					</div>
				</div>
				
				
			</div>
		</div>
	</section>
    <!--Newsleter Section-->
    <?php include "includes/newsletter.php"; ?>
    <!--End Newsleter Section-->

	<?php include "includes/footer.php"; ?>
</body>
</html>